/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa_20130803_proyecto_01;

import java.text.DecimalFormat;
import java.util.HashSet;
import java.util.Random;
import java.util.Set;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cgl05
 */
public class PA_20130803_Frame_01 extends javax.swing.JFrame {

    /**
     * Creates new form PA_20130803_Frame_01
     */
    
    DecimalFormat df = new DecimalFormat("###,###.00");
    Random azar = new Random();
    
    public PA_20130803_Frame_01() {
        initComponents();
        
        jTableDimensiones.setShowGrid(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDimensiones = new javax.swing.JTable();
        jSpinLocales = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jButCalcular = new javax.swing.JButton();
        jLabPromFrente = new javax.swing.JLabel();
        jLabTotalPerimetro = new javax.swing.JLabel();
        jLabPromFondo = new javax.swing.JLabel();
        jLabTotalArea = new javax.swing.JLabel();
        jButAleatorios = new javax.swing.JButton();
        jButEjemplo = new javax.swing.JButton();
        jCheckBoxAlfabetico = new javax.swing.JCheckBox();
        jCheckBoxAsendenteFrente = new javax.swing.JCheckBox();
        jCheckBoxDescendenteArea = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jButOrdenar = new javax.swing.JButton();
        jLabMayorFrente = new javax.swing.JLabel();
        jLabMenorFrente = new javax.swing.JLabel();
        jLabMayorArea = new javax.swing.JLabel();
        jLabMenorArea = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButMayorMenor = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableDimensiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Frente", "Fondo", "Area", "Perimetro"
            }
        ));
        jScrollPane1.setViewportView(jTableDimensiones);
        if (jTableDimensiones.getColumnModel().getColumnCount() > 0) {
            jTableDimensiones.getColumnModel().getColumn(0).setPreferredWidth(100);
        }

        jSpinLocales.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinLocalesStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Numero de locales");

        jButCalcular.setText("Calcular");
        jButCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCalcularActionPerformed(evt);
            }
        });

        jLabPromFrente.setBackground(new java.awt.Color(153, 255, 153));
        jLabPromFrente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabPromFrente.setOpaque(true);

        jLabTotalPerimetro.setBackground(new java.awt.Color(153, 255, 153));
        jLabTotalPerimetro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabTotalPerimetro.setOpaque(true);

        jLabPromFondo.setBackground(new java.awt.Color(153, 255, 153));
        jLabPromFondo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabPromFondo.setOpaque(true);

        jLabTotalArea.setBackground(new java.awt.Color(153, 255, 153));
        jLabTotalArea.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabTotalArea.setOpaque(true);

        jButAleatorios.setText("Aleatorios");
        jButAleatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAleatoriosActionPerformed(evt);
            }
        });

        jButEjemplo.setText("Ejemplo");
        jButEjemplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButEjemploActionPerformed(evt);
            }
        });

        jCheckBoxAlfabetico.setText("Alfabeticamente por nombre");

        jCheckBoxAsendenteFrente.setText("Asendente de acuerdo al Frente");

        jCheckBoxDescendenteArea.setText("Descendente de acuerdo al Area");
        jCheckBoxDescendenteArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxDescendenteAreaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Seleccione UNA opcion de ordenamiento:");

        jButOrdenar.setText("Ordenar");
        jButOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButOrdenarActionPerformed(evt);
            }
        });

        jLabMayorFrente.setBackground(new java.awt.Color(255, 255, 102));
        jLabMayorFrente.setOpaque(true);

        jLabMenorFrente.setBackground(new java.awt.Color(255, 255, 102));
        jLabMenorFrente.setOpaque(true);

        jLabMayorArea.setBackground(new java.awt.Color(255, 255, 102));
        jLabMayorArea.setOpaque(true);

        jLabMenorArea.setBackground(new java.awt.Color(255, 255, 102));
        jLabMenorArea.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Promedio de Frente");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Promedio de Fondo");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Area Total");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Perimetro Total");

        jButMayorMenor.setText("Mayor Y Menor");
        jButMayorMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButMayorMenorActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pa_20130803_proyecto_01/Asignacion.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pa_20130803_proyecto_01/Ejemplo POO P1_21_1 EneJun. Locales comerciales.jpg"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Datos del Proyecto:");

        jLabel10.setText("Nombre: Carson Alejandro Gómez Lugo");

        jLabel11.setText("Numero de Control: 20130803");

        jLabel12.setText("Numero del proyecto: 01");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Descripcion de la aplicacion: ");

        jLabel14.setText("La aplicacion te pemite obtener frente y ");

        jLabel15.setText("area, ingresando fondo y perimetro, ");

        jLabel16.setText("asi como un ordenamiento a seleccion de");

        jLabel17.setText("del usuario, y el nombre de mayor y menor");

        jLabel18.setText("de acuerdo a frente y area.");

        jButBorrar.setBackground(new java.awt.Color(255, 51, 51));
        jButBorrar.setText("Borrar");
        jButBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSpinLocales, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButCalcular)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButAleatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButEjemplo)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBoxDescendenteArea)
                                            .addComponent(jLabel2)
                                            .addComponent(jCheckBoxAlfabetico)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jCheckBoxAsendenteFrente)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButOrdenar)))
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addComponent(jLabel8))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel12)
                                                    .addComponent(jLabel10))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel18)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(22, 22, 22))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabMayorFrente, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabMenorFrente, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabMayorArea, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabMenorArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(jButMayorMenor)
                                        .addGap(143, 143, 143)
                                        .addComponent(jLabel3)
                                        .addGap(134, 134, 134)
                                        .addComponent(jLabel4))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(300, 300, 300)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabPromFrente, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(84, 84, 84)
                                        .addComponent(jLabPromFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(74, 74, 74)
                                        .addComponent(jLabTotalArea, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(112, 112, 112)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel6))
                                    .addComponent(jLabTotalPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jSpinLocales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jButCalcular)
                                    .addComponent(jButAleatorios)
                                    .addComponent(jButEjemplo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButBorrar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBoxAlfabetico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBoxAsendenteFrente)
                                    .addComponent(jButOrdenar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxDescendenteArea))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabTotalArea, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabTotalPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabPromFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabPromFrente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButMayorMenor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabMayorFrente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabMenorFrente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabMayorArea, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabMenorArea, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinLocalesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinLocalesStateChanged
        // TODO add your handling code here:
        int cantidad = (int)jSpinLocales.getValue();
        
        DefaultTableModel modelo = (DefaultTableModel) jTableDimensiones.getModel();
        
        modelo.setRowCount(cantidad);
        
    }//GEN-LAST:event_jSpinLocalesStateChanged

    private void jButCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCalcularActionPerformed
        // TODO add your handling code here:
        double promFrente=0,promFondo=0,totalArea=0,totalPerimetro=0;
        
        Local loc = new Local();
        
        for (int r = 0; r < jTableDimensiones.getRowCount(); r++) 
        {
            
            loc.setNombre(jTableDimensiones.getValueAt(r,0)+"");                           
            loc.setFondo(Double.parseDouble(jTableDimensiones.getValueAt(r, 2)+""));                             
            loc.setPerimetro(Double.parseDouble(jTableDimensiones.getValueAt(r, 4)+""));
            
            jTableDimensiones.setValueAt(loc.frente(), r, 1);
            loc.setFrente(Double.parseDouble(jTableDimensiones.getValueAt(r, 1)+ ""));
            
            jTableDimensiones.setValueAt(loc.area(), r, 3);
            loc.setArea(Double.parseDouble(jTableDimensiones.getValueAt(r, 3)+ ""));
                
            promFrente += loc.getFrente();
            promFondo += loc.getFondo();
            totalArea += loc.getArea();
            totalPerimetro += loc.getPerimetro();
        }
        
        promFrente /= jTableDimensiones.getRowCount();
        promFondo /= jTableDimensiones.getRowCount();
        
        jLabPromFrente.setText(df.format(promFrente)+"");
        jLabPromFondo.setText(df.format(promFondo)+"");
        jLabTotalArea.setText(df.format(totalArea)+"");
        jLabTotalPerimetro.setText(df.format(totalPerimetro)+"");
        
    }//GEN-LAST:event_jButCalcularActionPerformed

    private void jButEjemploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButEjemploActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) jTableDimensiones.getModel();
        
        modelo.setRowCount(4);
                        
        jTableDimensiones.setValueAt("Telcel", 0, 0);
        jTableDimensiones.setValueAt(50.00, 0, 2);
        jTableDimensiones.setValueAt(150.00, 0, 4);
        
        jTableDimensiones.setValueAt("C&A", 1, 0);
        jTableDimensiones.setValueAt(60.00, 1, 2);
        jTableDimensiones.setValueAt(180.00, 1, 4);
        
        jTableDimensiones.setValueAt("Zara", 2, 0);
        jTableDimensiones.setValueAt(35.00, 2, 2);
        jTableDimensiones.setValueAt(100.00, 2, 4);
        
        jTableDimensiones.setValueAt("Mc Donald's", 3, 0);
        jTableDimensiones.setValueAt(8.00, 3, 2);
        jTableDimensiones.setValueAt(56.00, 3, 4);
        
    }//GEN-LAST:event_jButEjemploActionPerformed

    private void jButAleatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAleatoriosActionPerformed
        // TODO add your handling code here:
       DefaultTableModel modelo = (DefaultTableModel) jTableDimensiones.getModel();
       
       modelo.setRowCount(azar.nextInt(12) + 2);
       
       String [] nombres = {"Burger King", "Mc Donald's", "Zara", "Cinepolis",
                            "Cinemex", "C&A", "Taco Taco", "Vegan Republic",
                            "Telcel", "Movistar", "Nives Chepo", "Tacostado",
                            "La blanquita", "Carl's Jr", "Chili's", "Cinnabon",
                            "Nutrisa", "AT&T", "Sushi Itto", "Oxxo", "7 eleven"};       
       
       for (int r = 0; r < jTableDimensiones.getRowCount(); r++) 
        {
            jTableDimensiones.setValueAt("", r, 1);
            jTableDimensiones.setValueAt("", r, 3);
            
            jTableDimensiones.setValueAt(nombres[azar.nextInt(nombres.length)], r, 0);
            jTableDimensiones.setValueAt(azar.nextInt(80)+25, r, 2);
            jTableDimensiones.setValueAt(azar.nextInt(200)+250, r, 4);                          
        }
       
    }//GEN-LAST:event_jButAleatoriosActionPerformed

    private void jCheckBoxDescendenteAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxDescendenteAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxDescendenteAreaActionPerformed

    private void jButOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButOrdenarActionPerformed
        // TODO add your handling code here:
        Local[] dimension = new Local[jTableDimensiones.getRowCount()];
        
        for (int r = 0; r < jTableDimensiones.getRowCount(); r++) 
        {           
            Local loc = new Local();
            
            loc.setNombre(jTableDimensiones.getValueAt(r,0)+"");            
            loc.setFrente(Double.parseDouble(jTableDimensiones.getValueAt(r, 1)+""));                
            loc.setFondo(Double.parseDouble(jTableDimensiones.getValueAt(r, 2)+""));                
            loc.setArea(Double.parseDouble(jTableDimensiones.getValueAt(r, 3)+""));                
            loc.setPerimetro(Double.parseDouble(jTableDimensiones.getValueAt(r, 4)+""));
            
            dimension[r] = loc;
        }
        
        if(jCheckBoxAlfabetico.isSelected())
        {
            for (int i = 0; i < dimension.length - 1; i++) 
                for (int j = i+1; j < dimension.length; j++)                 
                    if(dimension[i].getNombre().compareTo(dimension[j].getNombre()) > 0)
                    {
                        Local aux = dimension[i];
                        dimension[i]= dimension[j];
                        dimension[j]= aux;
                    }
        }
        
        if(jCheckBoxAsendenteFrente.isSelected())
        {
            for (int i = 0; i < dimension.length - 1; i++) 
                for (int j = i+1; j < dimension.length; j++)                 
                    if(dimension[i].getFrente() > dimension[j].getFrente())
                    {
                        Local aux = dimension[i];
                        dimension[i]= dimension[j];
                        dimension[j]= aux;
                    }
        }
        
        if(jCheckBoxDescendenteArea.isSelected())
        {
            for (int i = 0; i < dimension.length - 1; i++) 
                for (int j = i+1; j < dimension.length; j++)                 
                    if(dimension[i].getArea() < dimension[j].getArea())
                    {
                        Local aux = dimension[i];
                        dimension[i]= dimension[j];
                        dimension[j]= aux;
                    }
        }
        
        for(int r = 0; r < dimension.length; r++) 
        {
            jTableDimensiones.setValueAt(dimension[r].getNombre(), r, 0);
            jTableDimensiones.setValueAt(dimension[r].getFrente(), r, 1);
            jTableDimensiones.setValueAt(dimension[r].getFondo(), r, 2);
            jTableDimensiones.setValueAt(dimension[r].getArea(), r, 3);
            jTableDimensiones.setValueAt(dimension[r].getPerimetro(), r, 4);
        }
                
    }//GEN-LAST:event_jButOrdenarActionPerformed

    private void jButMayorMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButMayorMenorActionPerformed
        // TODO add your handling code here:        
        Local mayorFrente = new Local();        
        Local menorFrente = new Local();
        
        Local mayorArea = new Local();        
        Local menorArea = new Local();
        
        for (int r = 0; r < jTableDimensiones.getRowCount(); r++) 
        {
            
            Local loc = new Local();
            
            loc.setNombre(jTableDimensiones.getValueAt(r,0)+"");                           
            loc.setFondo(Double.parseDouble(jTableDimensiones.getValueAt(r, 2)+""));                             
            loc.setPerimetro(Double.parseDouble(jTableDimensiones.getValueAt(r, 4)+""));
            
            loc.setFrente(loc.frente());           
            
            if(r==0)
            {
                mayorFrente = loc;
                menorFrente = loc;
                mayorArea = loc;
                menorArea = loc; 
            }
            
            if(loc.frente() > mayorFrente.frente())
                mayorFrente = loc;
            
            if(loc.frente() < menorFrente.frente())
                menorFrente = loc;
            
            if(loc.area() > mayorArea.area())
                mayorArea = loc;
            
            if(loc.area() < menorArea.area())
                menorArea = loc;
            
        }
        
        jLabMayorFrente.setText("Quien tiene el mayor frente es " + mayorFrente.getNombre());
        jLabMenorFrente.setText("Quien tiene el menor frente es " + menorFrente.getNombre());        
        jLabMayorArea.setText("Quien tiene la mayor area es " + mayorArea.getNombre());
        jLabMenorArea.setText("Quien tiene la menor area es " + menorArea.getNombre());
        
    }//GEN-LAST:event_jButMayorMenorActionPerformed

    private void jButBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButBorrarActionPerformed
        // TODO add your handling code here:
        for(int r = 0; r < jTableDimensiones.getRowCount(); r++)
            for(int c = 0; c < jTableDimensiones.getColumnCount(); c++)
            {
                jTableDimensiones.setValueAt("", r, c);
                
                jLabMayorFrente.setText("");
                jLabMenorFrente.setText("");        
                jLabMayorArea.setText("");
                jLabMenorArea.setText("");
                
                jLabPromFrente.setText("");
                jLabPromFondo.setText("");
                jLabTotalArea.setText("");
                jLabTotalPerimetro.setText("");
                
            }
                    
    }//GEN-LAST:event_jButBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PA_20130803_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PA_20130803_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PA_20130803_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PA_20130803_Frame_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PA_20130803_Frame_01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAleatorios;
    private javax.swing.JButton jButBorrar;
    private javax.swing.JButton jButCalcular;
    private javax.swing.JButton jButEjemplo;
    private javax.swing.JButton jButMayorMenor;
    private javax.swing.JButton jButOrdenar;
    private javax.swing.JCheckBox jCheckBoxAlfabetico;
    private javax.swing.JCheckBox jCheckBoxAsendenteFrente;
    private javax.swing.JCheckBox jCheckBoxDescendenteArea;
    private javax.swing.JLabel jLabMayorArea;
    private javax.swing.JLabel jLabMayorFrente;
    private javax.swing.JLabel jLabMenorArea;
    private javax.swing.JLabel jLabMenorFrente;
    private javax.swing.JLabel jLabPromFondo;
    private javax.swing.JLabel jLabPromFrente;
    private javax.swing.JLabel jLabTotalArea;
    private javax.swing.JLabel jLabTotalPerimetro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinLocales;
    private javax.swing.JTable jTableDimensiones;
    // End of variables declaration//GEN-END:variables
}
